# -*- coding: utf-8 -*-
"""
Legend strings.

"""

helen = {'363434': {'code': 17,
              'colour': None,
              'grainsize': None,
              'lithology': 'Coal',
              'map colour': '#363434',
              'summary': 'Coal',
              'width': 1},
             '664A4A': {'code': 12,
              'colour': 'Red',
              'grainsize': None,
              'lithology': 'Mudstone',
              'map colour': '#664A4A',
              'summary': 'Mudstone, Red',
              'width': 1},
             '666666': {'code': 11,
              'colour': 'Grey',
              'grainsize': None,
              'lithology': 'Mudstone',
              'map colour': '#666666',
              'summary': 'Mudstone, Grey',
              'width': 1},
             '86F0B6': {'code': 1,
              'colour': None,
              'grainsize': None,
              'lithology': 'Conglomerate',
              'map colour': '#86F0B6',
              'summary': 'Conglomerate',
              'width': 3},
             'A1655A': {'code': 8,
              'colour': 'Red',
              'grainsize': None,
              'lithology': 'Siltstone',
              'map colour': '#A1655A',
              'summary': 'Siltstone, Red',
              'width': 3},
             'A657FA': {'code': 14,
              'colour': None,
              'grainsize': None,
              'lithology': 'Dolomite',
              'map colour': '#A657FA',
              'summary': 'Dolomite',
              'width': 2},
             'A68374': {'code': 7,
              'colour': 'Grey',
              'grainsize': None,
              'lithology': 'Siltstone',
              'map colour': '#A68374',
              'summary': 'Siltstone, Grey',
              'width': 3},
             'A6D1FF': {'code': 13,
              'colour': None,
              'grainsize': None,
              'lithology': 'Limestone',
              'map colour': '#A6D1FF',
              'summary': 'Limestone',
              'width': 3},
             'DBC9BC': {'code': 10,
              'colour': 'Red',
              'grainsize': None,
              'lithology': 'Heterolithic',
              'map colour': '#DBC9BC',
              'summary': 'Heterolithic, Red',
              'width': 2},
             'DBD6BC': {'code': 9,
              'colour': 'Grey',
              'grainsize': None,
              'lithology': 'Heterolithic',
              'map colour': '#DBD6BC',
              'summary': 'Heterolithic, Grey',
              'width': 2},
             'F2FF42': {'code': 4,
              'colour': 'Grey',
              'grainsize': 'F-M',
              'lithology': 'Sandstone',
              'map colour': '#F2FF42',
              'summary': 'Sandstone, F-M, Grey',
              'width': 3},
             'F7E9A6': {'code': 5,
              'colour': 'Grey',
              'grainsize': 'VF-F',
              'lithology': 'Sandstone',
              'map colour': '#F7E9A6',
              'summary': 'Sandstone, VF-F, Grey',
              'width': 3},
             'FF4C4A': {'code': 18,
              'colour': None,
              'grainsize': None,
              'lithology': 'Volcanic',
              'map colour': '#FF4C4A',
              'summary': 'Volcanic',
              'width': 2},
             'FF96F6': {'code': 16,
              'colour': None,
              'grainsize': None,
              'lithology': 'Halite',
              'map colour': '#FF96F6',
              'summary': 'Halite',
              'width': 2},
             'FF99CC': {'code': 15,
              'colour': None,
              'grainsize': None,
              'lithology': 'Anhydrite',
              'map colour': '#FF99CC',
              'summary': 'Anhydrite',
              'width': 2},
             'FFD073': {'code': 3,
              'colour': 'Red',
              'grainsize': 'C-M',
              'lithology': 'Sandstone',
              'map colour': '#FFD073',
              'summary': 'Sandstone, C-M, Red',
              'width': 3},
             'FFDBBA': {'code': 6,
              'colour': 'Red',
              'grainsize': 'VF-F',
              'lithology': 'Sandstone',
              'map colour': '#FFDBBA',
              'summary': 'Sandstone, VF-F, Red',
              'width': 3},
             'FFE040': {'code': 2,
              'colour': 'Grey',
              'grainsize': 'C-M',
              'lithology': 'Sandstone',
              'map colour': '#FFE040',
              'summary': 'Sandstone, C-M, Grey',
              'width': 3},
             'FFFFFF': {'code': 19,
              'colour': None,
              'grainsize': None,
              'lithology': 'NULL',
              'map colour': '#FFFFFF',
              'summary': 'NULL',
              'width': 0}}

legend = {'363434': {'code': 17,
              'colour': None,
              'grainsize': None,
              'lithology': 'Coal',
              'map colour': '#363434',
              'summary': 'Coal',
              'width': 1},
             '664A4A': {'code': 12,
              'colour': 'Red',
              'grainsize': None,
              'lithology': 'Mudstone',
              'map colour': '#664A4A',
              'summary': 'Mudstone, Red',
              'width': 1},
             '666666': {'code': 11,
              'colour': 'Grey',
              'grainsize': None,
              'lithology': 'Mudstone',
              'map colour': '#666666',
              'summary': 'Mudstone, Grey',
              'width': 1},
             '86F0B6': {'code': 1,
              'colour': None,
              'grainsize': None,
              'lithology': 'Conglomerate',
              'map colour': '#86F0B6',
              'summary': 'Conglomerate',
              'width': 5},
             'A1655A': {'code': 8,
              'colour': 'Red',
              'grainsize': None,
              'lithology': 'Siltstone',
              'map colour': '#A1655A',
              'summary': 'Siltstone, Red',
              'width': 2},
             'A657FA': {'code': 14,
              'colour': None,
              'grainsize': None,
              'lithology': 'Dolomite',
              'map colour': '#A657FA',
              'summary': 'Dolomite',
              'width': 3},
             'A68374': {'code': 7,
              'colour': 'Grey',
              'grainsize': None,
              'lithology': 'Siltstone',
              'map colour': '#A68374',
              'summary': 'Siltstone, Grey',
              'width': 2},
             'A6D1FF': {'code': 13,
              'colour': None,
              'grainsize': None,
              'lithology': 'Limestone',
              'map colour': '#A6D1FF',
              'summary': 'Limestone',
              'width': 3},
             'DBC9BC': {'code': 10,
              'colour': 'Red',
              'grainsize': None,
              'lithology': 'Heterolithic',
              'map colour': '#DBC9BC',
              'summary': 'Heterolithic, Red',
              'width': 3},
             'DBD6BC': {'code': 9,
              'colour': 'Grey',
              'grainsize': None,
              'lithology': 'Heterolithic',
              'map colour': '#DBD6BC',
              'summary': 'Heterolithic, Grey',
              'width': 3},
             'F2FF42': {'code': 4,
              'colour': 'Grey',
              'grainsize': 'F-M',
              'lithology': 'Sandstone',
              'map colour': '#F2FF42',
              'summary': 'Sandstone, F-M, Grey',
              'width': 4},
             'F7E9A6': {'code': 5,
              'colour': 'Grey',
              'grainsize': 'VF-F',
              'lithology': 'Sandstone',
              'map colour': '#F7E9A6',
              'summary': 'Sandstone, VF-F, Grey',
              'width': 3},
             'FF4C4A': {'code': 18,
              'colour': None,
              'grainsize': None,
              'lithology': 'Volcanic',
              'map colour': '#FF4C4A',
              'summary': 'Volcanic',
              'width': 2},
             'FF96F6': {'code': 16,
              'colour': None,
              'grainsize': None,
              'lithology': 'Halite',
              'map colour': '#FF96F6',
              'summary': 'Halite',
              'width': 2},
             'FF99CC': {'code': 15,
              'colour': None,
              'grainsize': None,
              'lithology': 'Anhydrite',
              'map colour': '#FF99CC',
              'summary': 'Anhydrite',
              'width': 2},
             'FFD073': {'code': 3,
              'colour': 'Red',
              'grainsize': 'C-M',
              'lithology': 'Sandstone',
              'map colour': '#FFD073',
              'summary': 'Sandstone, C-M, Red',
              'width': 4},
             'FFDBBA': {'code': 6,
              'colour': 'Red',
              'grainsize': 'VF-F',
              'lithology': 'Sandstone',
              'map colour': '#FFDBBA',
              'summary': 'Sandstone, VF-F, Red',
              'width': 3},
             'FFE040': {'code': 2,
              'colour': 'Grey',
              'grainsize': 'C-M',
              'lithology': 'Sandstone',
              'map colour': '#FFE040',
              'summary': 'Sandstone, C-M, Grey',
              'width': 4},
             'FFFFFF': {'code': 19,
              'colour': None,
              'grainsize': None,
              'lithology': 'NULL',
              'map colour': '#FFFFFF',
              'summary': 'NULL',
              'width': 0}}